# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 87868b59ede830b9012054906465adf0437361d867f7a174309a43fba0a5f6a8513595492f9470358bfbd3114cdae9417aba914bd594f0626a20e5a334848d01

test:
  secret_key_base: f48d6ff89565754bc6588d012be6efbaa0dabe760ccb3026c4ec25a26f1038850ba268991dd5f5f9dcd30e0b6ec92b48678f32ef11ef01f64373c3d48f6c10a5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["secret_key_base"] %>
